# Generated by Django 2.0.4 on 2018-04-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='photo',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
    ]
